name: Deploy to production


on:
  push:
    branches: [ main ]

  workflow_dispatch:


jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v18

      - name: Cache elm home
        uses: actions/cache@v3
        env:
          cache-name: cache-elm-home
        with:
          path: ~/.elm
          key: ${{ runner.os }}-elm-home-${{ hashFiles('**/elm.json') }}

      - name: Install Dependencies
        run: nix-shell --run "just install-deps"

      - name: Build
        run: nix-shell --run "just production-build"

      - name: Publish to Fission
        uses: fission-codes/publish-action@v1
        with:
          machine_key: ${{ secrets.FISSION_PRODUCTION_KEY }}
          build_dir: ./build
          app_url: drive.fission.app
